FROM openjdk:11
COPY . /usr
WORKDIR /usr
CMD ["java", "-jar", "target/learning-jdbc-1.0-SNAPSHOT.jar"]

#COPY target/jdbc*.jar /usr/local/app/jdbc/lib/jdbc.jar
#ENTRYPOINT ["java","-jar","/usr/local/app/jdbc/lib/jdbc.jar"]
#RUN javac Main.java
#CMD ["java", "Main"]
